### ISSUE TITLE
.button is not a function error on jquery-ui@1.12.0

### ISSUE THREAD

**Issue by mohak1990** [tamble/jquery-ui-daterangepicker#66] opened 2016-08-31 11:33 UTC
jquery-ui-daterangepicker breaks with the error 

TypeError: $(...).addClass(...).attr(...).button is not a function
$self = $('<button type="button"></button>')

This error appears on the latest jquery-ui

**Comment by op16** [comment] 2016-08-31 17:24
Sorry, I can't reproduce your issue.

Maybe you are using a custom jqueryUI download, which doesn't includes all the required widgets (like button), or maybe your are using other JS libraries like bootstrap.js.

However, there are known issues with versions of jqueryUI more recent than 1.10.3, which will hopefully be addressed by late September.

**Comment by mohak1990** [comment] 2016-09-02 07:00
I'm using jquery-ui 1.12.0.. it works well in Previous versions.. hope this issue gets addressed in the upcoming version..

**Comment by richakhurana19** [comment] 2016-12-26 07:59
I am facing the same issue while integrating the component with Primefaces which internally bundles jquery-ui-1.11.0. Eagerly awaiting the fix

**Comment by op16** [comment] 2017-01-12 17:41
@richakhurana19 The jquery-ui bundled in Primefaces doesn't include all required widgets, namely button & menu. I suppose they had some serious reason not to include them.

Either way, it's not the jquery-ui version, but the missing plugins which are causing the `TypeError: $(...).addClass(...).attr(...).button is not a function`.

 The known issues I was talking above are all CSS-related.

**Closed** 2017-01-18 21:35 UTC
